### PR TITLE
Add Curiosity Nano programmer and avrdude entries

### PR DESCRIPTION
**Pull request by WestfW**
Add Curiosity Nano to both the programmers.txt file and to the avrdude.conf file, so that these can be used without loading optiboot.

Tested with both a CN ATtiny3217 and a CN Attint1607

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Oh sick!

**Comment by MCUdude** [comment]
There is already a curiosity nano programmer target in programmers.txt: `Atmel nEDBG (ATSAMD21E18)`. However, @SpenceKonde forgot to add this to the avrdude.conf file, so this programmer option probably doesn't work.

**Comment by SpenceKonde** [comment]
I didn't "forget", I didn't know that the entry wasn't in avrdude.conf - I cannot keep track of all these programmers, which seem to be known by at least three different names each and often embedded in multiple official development boards. Can you tell me or point me to something describing what I need to do? Or even better, list of them, and what they are and what devboards the  come with....

**Comment by MCUdude** [comment]
> Can you tell me or point me to something describing what I need to do? Or even better, list of them, and what they are and what devboards the come with....

I'll do my best.

* The ATmega32u4 based mEDBG programmer :
  - ATtiny817 Xplained Mini
  - ATtiny416 Xplained Nano
  - Arduino Uno Wifi Rev2
  - microUPDI programmer
* The SAMD21 based nEDBG programmer can be found on most Curiosity Nano boards:
  - ATmega4809 Curiosity Nano
  - ATtiny1607 Curiosity Nano
  - ATtiny3217 Curiosity Nano
  - AVR18DA48 Curiosity Nano

Instead of merging @westfw's PR, you should add this to avrdude.conf instead:

```
programmer
  id    = "curiosity_updi";
  desc  = "Curiosity in UPDI mode";
  type  = "jtagice3_updi";
  connection_type = usb;
  usbpid = 0x2175;
;
```
https://github.com/MCUdude/MegaCoreX/blob/769519eceb56eaa18b61d64ef1a0ae4ab7c25c80/megaavr/avrdude.conf#L1162-L1168
<br>
By adding this, your existing nEDBG programmer option will work:

https://github.com/SpenceKonde/megaTinyCore/blob/ec6518417d1703f00c3435bc91e09254ff69aa27/megaavr/programmers.txt#L15-L20

**Pull request merged**
