### PR TITLE
fully add 2mhz non-tuned to all sections of boards.txt, adjust OSCCFG to 20MHZ and DIV from 1mhz to 2mhz

### PR DESCRIPTION
**Pull request by ObviousInRetrospect**
Not sure it is possible to correctly edit boards.txt but I think I found all 54 changes needed. Replaced the incorrect x16 div with a x10 div and adjusted the OSCCFG to use the 20mhz osc.

Also adjusted the OSCCFG for the tuned ones that were in there over and added a 2tuned to the 14-pin parts. Although less sure that will work, don't know if additional changes are needed for tuning. It looks like supported tuned speeds are not the same for all parts.

### CODE REVIEW

**Comment by ObviousInRetrospect** [comment]
(this has not been tested since I don't know how to do the upgrade to Azduino5 toolchain).

The failing checks seem to fail on something that seems unrelated:

Compiling sketch: megaavr/libraries/Logic/examples/Oscillate
[1236](https://github.com/SpenceKonde/megaTinyCore/runs/7551428518?check_suite_focus=true#step:3:1302)
  Warning: Board megaTinyCore:megaavr:atxy70 doesn't define a 'build.board' preference. Auto-set to: MEGAAVR_ATXY70
[1237](https://github.com/SpenceKonde/megaTinyCore/runs/7551428518?check_suite_focus=true#step:3:1303)
  In file included from /home/runner/.arduino15/packages/megaTinyCore/hardware/megaavr/2.5.11/libraries/Event/src/Event.h:47:0,
[1238](https://github.com/SpenceKonde/megaTinyCore/runs/7551428518?check_suite_focus=true#step:3:1304)
                   from /home/runner/work/megaTinyCore/megaTinyCore/megaavr/libraries/Logic/examples/Oscillate/Oscillate.ino:58:
[1239](https://github.com/SpenceKonde/megaTinyCore/runs/7551428518?check_suite_focus=true#step:3:1305)
  /home/runner/.arduino15/packages/megaTinyCore/hardware/megaavr/2.5.11/libraries/Event/src/Event_get_set_alias.h:20:37: error: 'event::gen1' has not been declared

**Comment by SpenceKonde** [comment]
I'm currently working on these and other problems, I think I have already fixed your problem.

**Comment by SpenceKonde** [comment]
I'm on the fence about whether this version will have a hand-edited boards.txt - I'm moving to autogenerating. If it does, it will be the last. It is absolutely and completely unmaintainable as a hand edited file. It has a size of  250k, but compresses to 25k .zip. It is a terribly inefficient file and it is , not meant to be written by hand my us mere mortals. It is verbose and requires line upon line upon line that are nearly identical except for the last bit.

**Comment by ObviousInRetrospect** [comment]
As much as I regretted not writing a python script to insert clock speeds which would have been faster than doing a single one by hand my vote is to defer that to vNext in favor of supporting DDs in DXCore since DDs are shipping and the DXCore docs say its basically done and shipping shortly.

**Comment by SpenceKonde** [comment]
Can you please present some data in support of your claim that the 20 MHz oscillator is more accurate? That is inconsistent with my findings. I just realized my tuning sketch is also totally hosed and I need to figure out why and fix it, because I was going to point you to it and ask you to send me the output from it (running at 16 MHz and 20 MHz - those are the only speeds it is ever suported at). Note also that we have no support implemented for prescaling external clocks and the clock menu is a mile long (and you can't get 1 MHz from 20 MHz, only from 16 MHz or 24 MHz - there's no div20 setting

**Comment by ObviousInRetrospect** [comment]
I'm not going to have statistical significance until I do this project: https://github.com/SpenceKonde/DxCore/discussions/306

Regardless of which is "better" we already have a slow option (1mhz) off the 16mhz osc so providing a slow option off the 20Mhz gives more flexibility.

The last 4 boards I built with ATTiny1614's produced gibberish over serial at 1mhz, 4mhz, and 8mhz but perfectly good serial at 5mhz and 10mhz. The last 2 boards I built with ATTiny3224s had the same result. Two of the boards were fixed by running with tuning. But I switched to running a sketch that steps through all the CAL values while printing serial and manually picking the middle readable one, writing that to user row, and loading it in setup() because tuning setup was a pain.

Here is the output from the serial tuner for the boards that were on my desk:

```
== board 1 ==
BOOT
F_CPU:5000000
BOOT CLKCTRL_OSC20MCALIBA:154
16@3: 4 | 16@5: 12 | 20@3: 9 | 20@5: 16
CLKCTRL_OSC20MCALIBA:154
USER_SIG:0B:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:D7:84:00:30:FF:3F:10:06:FF:FF
FUSES: 00:00:02:FF:00:C5:04:00:00
==================
if this is corruption free the default tuning is acceptable

<gibberish @4@boot>
============ 12 (iv:154) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:154
16@3: 4 | 16@5: 12 | 20@3: 9 | 20@5: 16
CLKCTRL_OSC20MCALIBA:140
USER_SIG:0B:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:D7:84:00:30:FF:3F:10:06:FF:FF
FUSES: 00:00:02:FF:00:C5:04:00:00
==================

== board 2 ==

BOOT CLKCTRL_OSC20MCALIBA:158
16@3: 4 | 16@5: 12 | 20@3: 252 | 20@5: 1
CLKCTRL_OSC20MCALIBA:158
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:B7:F0:06:2E:FF:3D:0F:06:FF:FF
FUSES: 00:00:02:FF:00:C5:04:00:00
==================
if this is corruption free the default tuning is acceptable

<gibberish @4@boot>
============= 15 (iv:158) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:158
16@3: 4 | 16@5: 12 | 20@3: 252 | 20@5: 1
CLKCTRL_OSC20MCALIBA:143
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:B7:F0:06:2E:FF:3D:0F:06:FF:FF
FUSES: 00:00:02:FF:00:C5:04:00:00
==================



==board 3===
BOOT
F_CPU:5000000
BOOT CLKCTRL_OSC20MCALIBA:156
16@3: 8 | 16@5: 16 | 20@3: 255 | 20@5: 4
CLKCTRL_OSC20MCALIBA:156
USER_SIG:0D:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:80:80:0D:1A:27:2A:00:0D:1A:27:2A:3B
REVID: 64
S/N: 51:51:57:34:33:20:77:15:06:23:FF:3F:10:05:FF:FF
FUSES: 00:00:02:FF:00:C5:04:00:00
==================
if this is corruption free the default tuning is acceptable

<gibberish @4@boot>
============= 14 (iv:156) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:156
16@3: 8 | 16@5: 16 | 20@3: 255 | 20@5: 4
CLKCTRL_OSC20MCALIBA:142
USER_SIG:0D:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:80:80:0D:1A:27:2A:00:0D:1A:27:2A:3B
REVID: 64
S/N: 51:51:57:34:33:20:77:15:06:23:FF:3F:10:05:FF:FF
FUSES: 00:00:02:FF:00:C5:04:00:00
==================


==board 4==
Same behavior as 1-3 but we are no longer on speaking terms after it’s bath in salt water

==board 5/3224==
BOOT
F_CPU:5000000
BOOT CLKCTRL_OSC20MCALIBA:68
16@3: 255 | 16@5: 255 | 20@3: 255 | 20@5: 255
CLKCTRL_OSC20MCALIBA:68
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 30:43:50:51:46:55:84:C3:0E:17:FF:42:10:05:FF:FF
FUSES: 00:00:02:FF:FF:F6:04:00:00
==================
if this is corruption free the default tuning is acceptable

<gibberish @4@boot>
============= 36 (iv:68) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:68
16@3: 255 | 16@5: 255 | 20@3: 255 | 20@5: 255
CLKCTRL_OSC20MCALIBA:36
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 30:43:50:51:46:55:84:C3:0E:17:FF:42:10:05:FF:FF
FUSES: 00:00:02:FF:FF:F6:04:00:00
==================


==board 6/3224==
Same as board 5 but seems to have wandered off my desk
```

I can't readily run my clock cal test because at boot serial is broken and if I set the correct calibration that invalidates the test.

**Comment by ObviousInRetrospect** [comment]
Here is the full serial tuner sketch:
```
#include <USERSIG.h>
#include <core_devices.h>

uint8_t initval;

void prt_sn(){
    Serial.print("REVID: ");
  #ifdef SIGROW_SERNUM15 // AVR Dx-series
#define SERLEN
  char major = 0x40 + (SYSCFG.REVID >> 4);
  Serial.print(major);
  Serial.println(SYSCFG.REVID & 0x0F);
  #else
  Serial.println('@' + SYSCFG.REVID);
  #endif
  Serial.print("S/N: ");
  volatile uint8_t *mptr = &SIGROW_SERNUM0;
  Serial.printHex(*mptr++);
  for (byte i = 0; i < 15; i++) {
    Serial.print(':');
    Serial.printHex(*mptr++);
  }
  Serial.println();
  Serial.print("FUSES: ");
  mptr = FUSES_START;
  Serial.printHex(*mptr++);
  for (byte i = 1; i < 9; i++) {
    Serial.print(':');
    Serial.printHex(*mptr++);
  }
  Serial.println();

}

void prtsig(){
  Serial.print("F_CPU:");
  Serial.println(F_CPU);
  Serial.print("BOOT CLKCTRL_OSC20MCALIBA:");
  Serial.println(initval);
  Serial.print("16@3: "); Serial.print(SIGROW_OSC16ERR3V);
  Serial.print(" | 16@5: "); Serial.print(SIGROW_OSC16ERR5V);
  Serial.print(" | 20@3: "); Serial.print(SIGROW_OSC20ERR3V);
  Serial.print(" | 20@5: "); Serial.println(SIGROW_OSC20ERR5V);
  Serial.print("CLKCTRL_OSC20MCALIBA:");
  Serial.println(CLKCTRL_OSC20MCALIBA);
  Serial.print("USER_SIG:");
  for(uint8_t i=0; i<USER_SIGNATURES_SIZE; i++){
    if(i) Serial.print(":");
    Serial.printHex(USERSIG.read(i));
  }
  Serial.println();
  prt_sn();
  Serial.println("==================");
}


void setup() {
  initval=CLKCTRL_OSC20MCALIBA;
  //USERSIG.write(0,15);
  //USERSIG.write(0,0xFF);
  Serial.swap(); //standard uart pins are the crystal
  Serial.begin(115200);//, SERIAL_TX_ONLY);

  Serial.println("BOOT");
  prtsig();
  Serial.println("if this is corruption free the default tuning is acceptable");
  for(int j=0; j<5; j++) Serial.println("The quick brown fox jumps over the lazy dog");
  Serial.println(); Serial.println();

  uint8_t cal = USERSIG.read(0);
  if(cal <64){
    _PROTECTED_WRITE(CLKCTRL_OSC20MCALIBA, cal);
    _NOP();_NOP();
    delay(100);
    Serial.println("if this is corruption free the current tuning is acceptable");
    Serial.print("initial:"); Serial.println(initval);
    for(int j=0; j<5; j++) Serial.println("The quick brown fox jumps over the lazy dog");
  }
  prtsig();



}

void loop() {
  for(int i=0; i<64; i++){
    _PROTECTED_WRITE(CLKCTRL_OSC20MCALIBA, i);
    _NOP();
    _NOP();
    delay(500);
    Serial.println();
    Serial.println();
    Serial.print("============= ");
    Serial.print(i);
    Serial.print(" (iv:");
    Serial.print(initval);
    Serial.println(") =============");
    prtsig();
  }
  delay(5000);

}

```

**Comment by ObviousInRetrospect** [comment]
Found board 6 and found another 3 t1614 boards to test.

For what its worth, I've tried 2 different PCB layouts for the 3224 and 3 different ones for the t1614. This is sufficiently consistent that I am starting to suspect a software bug in megaTinyCore. Or the following sketch:

```
uint8_t initval;
void setup() {
  initval=CLKCTRL_OSC20MCALIBA;
  Serial.swap(); //standard uart pins are the crystal
  Serial.begin(115200);
  Serial.println("BOOT");
}

void loop(){}
```
(not really suspecting a bug in the above).

What sort of shape is head of tree in? Given that serial was reworked should I try it? Are there manual setup directions?

```
==board 6/3224==
Same as board 5 but seems to have wandered off my desk. Found it:

BOOT
F_CPU:5000000
BOOT CLKCTRL_OSC20MCALIBA:53
16@3: 255 | 16@5: 255 | 20@3: 255 | 20@5: 255
CLKCTRL_OSC20MCALIBA:53
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 30:43:50:51:46:55:04:11:35:10:FF:49:0D:05:FF:FF
FUSES: 00:00:02:FF:FF:F6:04:00:00
==================
if this is corruption free the default tuning is acceptable

<gibberish @4@boot>
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
QuX$␄KZ`H`TQtIVdX^␕F␂QHB#mG1iPBAIY@^dK␃hJ	P␃I␃iJ	@␃[␃iJEFV:YDaV$Y£lFJCJT	SLLLLLCLCMMMMLLLLCLCLMMMLLLLLCLCLMMMKI␃xTYu5mHmM	x[xJeK␓aMeMyHySaL␃MeMj5SEZG@`MaMiMj5j5jhHaX␃aFuNuNuNuNuNuNTT
============= 24 (iv:53) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:53
16@3: 255 | 16@5: 255 | 20@3: 255 | 20@5: 255
CLKCTRL_OSC20MCALIBA:24
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 30:43:50:51:46:55:04:11:35:10:FF:49:0D:05:FF:FF
FUSES: 00:00:02:FF:FF:F6:04:00:00
==================


== board 7 back to 1614==

BOOT
F_CPU:5000000
BOOT CLKCTRL_OSC20MCALIBA:162
16@3: 7 | 16@5: 15 | 20@3: 7 | 20@5: 14
CLKCTRL_OSC20MCALIBA:162
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:97:8C:06:3B:FF:41:10:05:FF:FF
FUSES: 00:00:02:00:C5:C4:04:00:00
==================
if this is corruption free the default tuning is acceptable
<gibberish @4@boot>
============= 17 (iv:162) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:162
16@3: 7 | 16@5: 15 | 20@3: 7 | 20@5: 14
CLKCTRL_OSC20MCALIBA:145
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:97:8C:06:3B:FF:41:10:05:FF:FF
FUSES: 00:00:02:00:C5:C4:04:00:00
==================


==board 8==
(Worked at 5, didn’t record output, lost track of which it was)
============= 18 (iv:162) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:162
16@3: 5 | 16@5: 12 | 20@3: 252 | 20@5: 2
CLKCTRL_OSC20MCALIBA:146
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:17:41:06:3A:FF:3E:10:06:FF:FF
FUSES: 00:00:02:FF:00:F6:04:00:00
==================


==board9==
BOOT
F_CPU:5000000
BOOT CLKCTRL_OSC20MCALIBA:162
16@3: 4 | 16@5: 13 | 20@3: 250 | 20@5: 0
CLKCTRL_OSC20MCALIBA:162
USER_SIG:12:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:17:07:05:30:FF:3A:12:05:FF:FF
FUSES: 00:00:02:FF:00:F7:04:00:00
==================
if this is corruption free the default tuning is acceptable
============= 18 (iv:162) =============
F_CPU:4000000
BOOT CLKCTRL_OSC20MCALIBA:162
16@3: 4 | 16@5: 13 | 20@3: 250 | 20@5: 0
CLKCTRL_OSC20MCALIBA:146
USER_SIG:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF
REVID: 64
S/N: 51:51:57:34:33:20:17:07:05:30:FF:3A:12:05:FF:FF
FUSES: 00:00:02:FF:00:F7:04:00:00
==================
```

**Comment by ObviousInRetrospect** [comment]
Unfortunately I just went back to Atmel Studio, built 2 identical atmel start projects one at 4mhz the other at 5mhz. The 4mhz one prints garbage. The 5mhz one prints fine. I have no idea WTF is going on but it doesn't look like a megaTinyCore bug.

**Comment by ObviousInRetrospect** [comment]
I'm guessing you no longer need the boards.txt changes with the new autogeneration but don't forget to fix wiring.c. Head of tree still has the 2mhz running at 1mhz. I now have far less strong of an opinion on 16 vs 20. I still think a mix is better but am not convinced it matters. The counter argument for 16 is automotive parts.

**Comment by ObviousInRetrospect** [comment]
closing this in favor of #759 which just fixes the wiring prescaler errors and does not attempt to change 2mhz to use the 20mhz.

**Pull request closed without merging**
