### PR TITLE
Add a new entry for the ATtiny412 with a wrong signature

### PR DESCRIPTION
**Pull request by juanfra684**
I've an ATtiny412 with a wrong signature:

```plain
avrdude: Device signature = 0x1e9221 (probably t416)
avrdude: Expected signature for ATtiny412 is 1E 92 23
         Double check chip, or use -F to override this check.

```

I've added a new entry to boards.txt and avrdude.conf, as was done for the 402 with the wrong signature. I can upload an sketch to the MCU without errors. However, there is something missing in my PR because `Burn Bootloader` is still using `-pattiny412` for the avrdude command.

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Heh, I don't think you missed anything, burn bootloader appears to be broken on the other bad-sig ones... easy fix (I just checked it into the core - the tools.avrdude.bootloader.pattern line needs the same reference to the workaround as program.pattern.

**Comment by juanfra684** [comment]
Thanks for the quick reply. I tested your change and `Burn bootloader` works fine now.

**Comment by SpenceKonde** [comment]
So there's another batch of wrong-sig chips making the rounds? I never heard of that being a thing with the classic AVRs, heh... 

Then again, they didn't make a whole shedload of parts from the same die either (212,214,412,414,416 are all the same die, as I understand; note how they have the same errata https://ww1.microchip.com/downloads/en/DeviceDoc/ATtiny212-214-412-414-416-SilConErrataClarif-DS80000933A.pdf (and also that Rev. C didn't fix a damned thing, and on the Errata sheet that came with its release, it actually sprouted a whole ton of new issues

**Comment by SpenceKonde** [comment]
Note - until I get another report of a wrong-sig 412 like this in the field, I'm going to hold off on the merge - I don't want to proliferate "wrongsig" variants that aren't really circulating in the wild.

**Comment by alunmorris** [comment]
I have a batch of ATTINY412 from Aliexpress with the T416 signature. They seems to have a T416 inside with the following pinout:
1 Vdd,  2 PA6 (Arduino D0, DAC) 3 PA7 (D3),  4 PB1 (D8, SDA),  5 PB0 (D9,SCL), 6  UPDI,  7 PA3 (D16),  8 GND
I have used them by programming as T416. There is No TxD, RxD or SPI.

**Comment by SpenceKonde** [comment]
Wow! 

Okay, that is.... interesting. 

If you do 
```
Serial.swap(1);
Serial.begin(115200); //or your favorite baud rate
```
you should get a serial port on PA1 and PA2 (the alternate serial pins). 

The real question in my mind is whether these are actually chips that Microchip intended to release or whether you got scammed by s dishonest vendor selling chips microchip tried to throw out... Assuming the serial port works with swap, can you run this code:

```
void setup() {
  Serial.swap(1);
  Serial.begin(115200);
  Serial.println();
  delay(1000);
  Serial.print("REVID: ");
  Serial.println(SYSCFG.REVID,HEX);
  volatile byte *ptr;
  ptr=&SIGROW.SERNUM0;
  for (byte i = 0; i < 16; i++ ) {
    if (i) Serial.print(':');
    Serial.print(*(ptr++),HEX);
  }
}
void loop() {;}
```

**Comment by alunmorris** [comment]
Spence,
The serial swap does not help. PA1,2 are not output. Tried and confirmed.I used an LCD on I2C and got:REVID 151:50:51:54:43:20:87:FF:FF:89:39:44:FF:41:10:5
Thanks very much for your tremendous work on megaTinyCore.The ATTINY402 is one of my favourite MPUs.I like minimalism..
Alun
    On Wednesday, 10 February 2021, 14:46:36 GMT, Spence Konde (aka Dr. Azzy) <notifications@github.com> wrote:  
 
 


Wow!

Okay, that is.... interesting.

If you do
Serial.swap(1);
Serial.begin(115200); //or your favorite baud rate

you should get a serial port on PA1 and PA2 (the alternate serial pins).

The real question in my mind is whether these are actually chips that Microchip intended to release or whether you got scammed by s dishonest vendor selling chips microchip tried to throw out... Assuming the serial port works with swap, can you run this code:
void setup() {
  Serial.swap(1);
  Serial.begin(115200);
  Serial.println();
  delay(1000);
  Serial.print("REVID: ");
  Serial.println(SYSCFG.REVID,HEX);
  volatile byte *ptr;
  ptr=&SIGROW.SERNUM0;
  for (byte i = 0; i < 16; i++ ) {
    if (i) Serial.print(':');
    Serial.print(*(ptr++),HEX);
  }
}
void loop() {;}

**Comment by juanfra684** [comment]
> I have a batch of ATTINY412 from Aliexpress with the T416 signature. They seems to have a T416 inside with the following pinout:
> 1 Vdd, 2 PA6 (Arduino D0, DAC) 3 PA7 (D3), 4 PB1 (D8, SDA), 5 PB0 (D9,SCL), 6 UPDI, 7 PA3 (D16), 8 GND
> I have used them by programming as T416. There is No TxD, RxD or SPI.

So, that's why a blink sketch worked in the pin 1 but failed in the pin 2. :facepalm: 

@SpenceKonde I used the SoftwareSerial library with your sketch. This is the output:

```plain
51:50:51:54:43:20:6A:2C:3D:54:FF:41:E:6:FF:FF REVID: 1
```

**Comment by SpenceKonde** [comment]
@juanfra684 You get yours from aliexpress too?

**Comment by alunmorris** [comment]
Sorry, I made a typo on pin 2. It should be PA6 (Arduino D2, DAC) not D0. 

Alun 
 
  On Wed, 10 Feb 2021 at 21:53, Spence Konde (aka Dr. Azzy)<notifications@github.com> wrote:   


@juanfra684 You get yours from aliexpress too?

**Comment by juanfra684** [comment]
> @juanfra684 You get yours from aliexpress too?

Yes.

**Comment by SpenceKonde** [comment]
Well, Let's see if Microchip support tells us anything, heh... I opened a ticket with them. I've sent them those serial numbers

@alunmorris - are you sure about the order of those? I'd try outputting it through software serial; I have a feeling that the bytes are out of order (artifact of printing them to LCD), and that it's actually
51:50:51:54:43:20:87:89:39:44:FF:41:10:5:FF:FF
These serial numbers have a pretty small amount of entropy (in other words, feel free to use it as a GUID - I do believe that they really are globally unique, but that's *ALL{* I'll give those numbers credit for :-P 
They haven't published the translation of which bytes mean what like they have for the DA-series, but, I think:
first 4 is a lot code
next two? They all ways seem to be 0x43, 0x20. 
Then 4 bytes that seem to have a lot of entropy (random numbers?), 
Next, a 0xFF (this is the 11th byte - note that the serial numbers are only 10 bytes long. Then immediately after that, three more non-0xFF bytes, but these seem to have very little entropy - the first looks like it's 0x40 or just over that, then something with a numeric value not far off from 0x10 (there's a 0x10 and 0x0E, ie, 16 and 14 here, a part I grabbed is showing 0x10 too. then a very low byte...

First 6 bytes could very well be ascii charachters if they're some nonsense/lookup table characters (yours comes out to like "QPQTC " and I've got a "QQ7AC " here, and so on.

I think there is a lesson here, and that is: Don't buy the jewelry of your project on aliexpress. If you want the basics, AliExpress away - but the good stuff? Modern microcontrollers, high performance anything, designer sunglasses? Buy em from a reputable distributor in the west! There were batches of fake ATtiny85's going around on there too recently.... (or "Only buy stuff so cheap it wouldn't be worth it to fake"

**Comment by alunmorris** [comment]
> @alunmorris - are you sure about the order of those? I'd try outputting it through software serial; I have a feeling that the bytes are out of order (artifact of printing them to LCD), and that it's actually
> 51:50:51:54:43:20:87:89:39:44:FF:41:10:5:FF:FF
Yes, you're right. Well, that LCD overflows in an unhelpful way!

**Comment by juanfra684** [comment]
> I think there is a lesson here, and that is: Don't buy the jewelry of your project on aliexpress. If you want the basics, AliExpress away - but the good stuff? Modern microcontrollers, high performance anything, designer sunglasses? Buy em from a reputable distributor in the west! There were batches of fake ATtiny85's going around on there too recently.... (or "Only buy stuff so cheap it wouldn't be worth it to fake"

Don't worry, at least in my case, it's not a big lost. The reason why I buy from Aliexpress is because they send the packages to the mailbox. I don't need to open the door to the mailman in the worst days of a pandemic.

Also, in my experience, they sell fakes even of the cheapest ICs. I've plenty of DIP ICs with the original marks deleted (with a laser?) and good quality new marks of a big brand. Funny thing is you can't find good chinese brands in Aliexpress.

**Comment by SpenceKonde** [comment]
I don't suppose either of you could come up with a good close-up photograph showing the markings on those chips for Microchip to examine? 

Thanks!

**Comment by alunmorris** [comment]
> I don't suppose either of you could come up with a good close-up photograph showing the markings on those chips for Microchip to examine?
https://drive.google.com/file/d/1kVtHmM9hA9XG6NZqhARBpSXewznF2rjT/view?usp=sharing

**Comment by juanfra684** [comment]
> I don't suppose either of you could come up with a good close-up photograph showing the markings on those chips for Microchip to examine?

[412.zip](https://github.com/SpenceKonde/megaTinyCore/files/6016346/412.zip)




I've added also a zip file with the original photo, just in case github compresses too much the photo.

**Comment by SpenceKonde** [comment]
No plans to change

**Pull request closed without merging**
